version: '3.3'
services:
    red_pack_productions:
        container_name: "red_pack_productions"
        image: "theyuwana/rpp-website:2.2.2"
        build:
            context: .
            dockerfile: ./docker_files/Dockerfile.compose
            args:
                MIX_ENV: prod
        working_dir: /application/red_pack_productions
        ports:
            - "80:80" 
        volumes:
            - .:/application:cached
        environment:
            MIX_ENV: prod
            PORT: 80
        command: /bin/bash /application/docker_files/docker_command.sh
